#!/bin/bash

echo "Enter changes made"

read message

cd ~/Developer/NetBeans/ChessAI/src/chessai/
cp *.java ~/Developer/GitHub/ChessAI/Java/
cd ~/Developer/GitHub/ChessAI/
git add -A
git commit -m "$message"
git push
